//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceTable
    {
        public int AbsenceID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public int ClassID { get; set; }
        public int StudentID { get; set; }
        public Nullable<System.DateTime> AbsenceDate { get; set; }
        public Nullable<System.DateTime> AbsenceRecordingDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool Status { get; set; }
        public string Justifcation { get; set; }
        public Nullable<int> GroupeId { get; set; }
        public Nullable<System.TimeSpan> AbsenceHour { get; set; }
    
        public virtual GroupeTable GroupeTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
