//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTime
    {
        public int ExamTimeId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> ClassSubjectID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ClassSubjectTable ClassSubjectTable { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        public virtual ExamTable ExamTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
