//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWorkTable
    {
        public int HomeWorkID { get; set; }
        public int HomeWorkTypeID { get; set; }
        public int ClassID { get; set; }
        public string HomeWorkTitle { get; set; }
        public string HomeWorkDescription { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public string DocPath { get; set; }
        public Nullable<int> GroupeID { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual GroupeTable GroupeTable { get; set; }
        public virtual HomeWorkTypeTable HomeWorkTypeTable { get; set; }
    }
}
