//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StaffTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffTable()
        {
            this.EmailstoStaff = new HashSet<EmailstoStaff>();
            this.EmployeeLeavingTable = new HashSet<EmployeeLeavingTable>();
            this.EmployeeSalaryTable = new HashSet<EmployeeSalaryTable>();
            this.StaffAbsence = new HashSet<StaffAbsence>();
            this.StaffAttendanceTable = new HashSet<StaffAttendanceTable>();
            this.TimeTblTable = new HashSet<TimeTblTable>();
        }
        [NotMapped]
        [Required(ErrorMessage = "{0} Required Field!")]
        public HttpPostedFileBase PhotoFile { get; set; }
        public int StaffID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public int DesignationID { get; set; }
        public string ContactNo { get; set; }
        public double BasicSalary { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Qualification { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Gender { get; set; }
        public string HomePhone { get; set; }
        public bool Doyouhaveanydisability { get; set; }
        public string Ifdisabilityyesthengiveusedtail { get; set; }
        public bool Areyoutakinganymedication { get; set; }
        public string Ifmedicationyesthengiveusdetail { get; set; }
        public bool AnyCriminaloffcenceagainstyou { get; set; }
        public string Ifcriminaloffcenceyesthengiveusdetail { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual DesignationTable DesignationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailstoStaff> EmailstoStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeavingTable> EmployeeLeavingTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalaryTable> EmployeeSalaryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAbsence> StaffAbsence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAttendanceTable> StaffAttendanceTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTblTable> TimeTblTable { get; set; }
    }
}
