//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAbsence
    {
        public int StaffAbsenceID { get; set; }
        public int StaffID { get; set; }
        public System.DateTime AbsenceStartDate { get; set; }
        public Nullable<System.DateTime> AbsenceEndDate { get; set; }
        public string Justification { get; set; }
        public bool Status { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual StaffTable StaffTable { get; set; }
    }
}
