//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.AbsenceTable = new HashSet<AbsenceTable>();
            this.EmailsToStudents = new HashSet<EmailsToStudents>();
            this.ExamMarksTable = new HashSet<ExamMarksTable>();
            this.SchoolLeavingTable = new HashSet<SchoolLeavingTable>();
            this.StudentPromotTable = new HashSet<StudentPromotTable>();
            this.SubmissionFeeTable = new HashSet<SubmissionFeeTable>();
        }
        [NotMapped]
        [Required(ErrorMessage = "{0} Required Field!")]
        public HttpPostedFileBase PhotoFile { get; set; }
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public int ProgrameID { get; set; }
        public int ClassID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public string CNIC { get; set; }
        public string FNIC { get; set; }
        public string Photo { get; set; }
        public System.DateTime AddmissionDate { get; set; }
        public string PreviousSchool { get; set; }
        public Nullable<double> PreviousPercentage { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string TribeorCaste { get; set; }
        public string FathersGuardiansOccupationofProfession { get; set; }
        public string FathersGuardiansPostalAddress { get; set; }
        public string PhoneOffice { get; set; }
        public string PhoneResident { get; set; }
        public Nullable<int> GroupeId { get; set; }
        public string FatherEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsenceTable> AbsenceTable { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailsToStudents> EmailsToStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTable { get; set; }
        public virtual GroupeTable GroupeTable { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLeavingTable> SchoolLeavingTable { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPromotTable> StudentPromotTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionFeeTable> SubmissionFeeTable { get; set; }
    }
}
