//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoTable
    {
        public int VideoId { get; set; }
        public string Title { get; set; }
        public string link { get; set; }
        public string Discription { get; set; }
        public int SubjectId { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
