//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DesignationTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesignationTable()
        {
            this.StaffTables = new HashSet<StaffTable>();
        }

        [Display(Name = "Designation ID:")]
        public int DesignationID { get; set; }
        [Display(Name = "User ID:")]
        public int UserID { get; set; }
        [Display(Name = "Title:")]
        public string Title { get; set; }
        [Display(Name = "Is Active:")]
        public bool IsActive { get; set; }

        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffTable> StaffTables { get; set; }
    }
}
