//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMarksTable
    {
        public int MarksID { get; set; }
        public int ExamID { get; set; }
        public int ClassSubjectID { get; set; }
        public int StudentID { get; set; }
        public int UserID { get; set; }
        public int TotalMarks { get; set; }
        public int ObtainMarks { get; set; }
    
        public virtual ClassSubjectTable ClassSubjectTable { get; set; }
        public virtual ExamTable ExamTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
