//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class HomeWorkTable
    {
        public int HomeWorkID { get; set; }
        [Display(Name = "Home-Work Type")]
        [Required(ErrorMessage = "Required!")]
        public int HomeWorkTypeID { get; set; }

        [Display(Name = "Student Class")]
        [Required(ErrorMessage = "Required!")]
        public int ClassID { get; set; }

        [Display(Name = "Student")]
        [Required(ErrorMessage = "Required!")]
        public int StudentID { get; set; }

        [Display(Name = "Home Work Title")]
        [Required(ErrorMessage = "Required!")]
        public string HomeWorkTitle { get; set; }

        [Display(Name = "Submit Date")]
        [Required(ErrorMessage ="Required!")]
        public string HomeWorkDescription { get; set; }

        [Display(Name = "Submit Date")]
        public System.DateTime SubmitDate { get; set; }
        public string DocPath { get; set; }

        //[NotMapped]
        //[Required(ErrorMessage = "Document File Required Field!")]
        public HttpPostedFileBase PhotoFile { get; set; }

        public virtual ClassTable ClassTable { get; set; }
        public virtual HomeWorkTypeTable HomeWorkTypeTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
