//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SessionTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionTable()
        {
            this.ProgrameSessionTables = new HashSet<ProgrameSessionTable>();
            this.StudentTables = new HashSet<StudentTable>();
        }

        [Display(Name = "SessionID:")]
        public int SessionID { get; set; }
        [Display(Name = "Created By:")]
        public int UserID { get; set; }
        [Display(Name = "Session:")]
        public string Name { get; set; }
        [Display(Name = "Start Date:")]
        [DataType(DataType.Date)]
        public System.DateTime StartDate { get; set; }
        [Display(Name = "End Date:")]
        [DataType(DataType.Date)]
        public System.DateTime EndDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgrameSessionTable> ProgrameSessionTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTable> StudentTables { get; set; }
    }
}
