//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StaffTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffTable()
        {
            this.EmployeeLeavingTables = new HashSet<EmployeeLeavingTable>();
            this.EmployeeSalaryTables = new HashSet<EmployeeSalaryTable>();
            this.StaffAttendanceTables = new HashSet<StaffAttendanceTable>();
            this.TimeTblTables = new HashSet<TimeTblTable>();
        }

        [Display(Name = "Staff ID:")]
        public int StaffID { get; set; }
        [Display(Name = "User ID:")]
        public int UserID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [Display(Name = "Name:")]
        public string Name { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [Display(Name = "Designation:")]
        public int DesignationID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [Display(Name = "Contact Number:")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Contact No Must be 11 Number")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]

        [Display(Name = "Basic Salary:")]
        public double BasicSalary { get; set; }
        [Display(Name = "Email Address:")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [Display(Name = "Address:")]

        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        [Display(Name = "Qualification:")]
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Qualification { get; set; }
        public string Photo { get; set; }
        [Display(Name = "Description:")]
        public string Description { get; set; }
        [Display(Name = "IsActive:")]
        public bool IsActive { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [Display(Name = "Gender:")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        [Display(Name = "Home Phone Number:")]
        public string HomePhone { get; set; }
        [Display(Name = "Do you have any disability ?")]
        public bool Doyouhaveanydisability { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Detail:")]
        public string Ifdisabilityyesthengiveusedtail { get; set; }
        [Display(Name = "Are you taking any medication ?")]
        public bool Areyoutakinganymedication { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Detail:")]
        public string Ifmedicationyesthengiveusdetail { get; set; }
        [Display(Name = "Do you have any police record ?")]
        public bool AnyCriminaloffcenceagainstyou { get; set; }
        [Display(Name = "Detail:")]
        [DataType(DataType.MultilineText)]
        public string Ifcriminaloffcenceyesthengiveusdetail { get; set; }
        [Display(Name = "Registration Date:")]
        public System.DateTime RegistrationDate { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "{0} Required Field!")]
        public HttpPostedFileBase PhotoFile { get; set; }
        public virtual DesignationTable DesignationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeavingTable> EmployeeLeavingTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalaryTable> EmployeeSalaryTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAttendanceTable> StaffAttendanceTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTblTable> TimeTblTables { get; set; }
    }
}
