//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.AttendanceTables = new HashSet<AttendanceTable>();
            this.SchoolLeavingTables = new HashSet<SchoolLeavingTable>();
            this.StudentPromotTables = new HashSet<StudentPromotTable>();
            this.SubmissionFeeTables = new HashSet<SubmissionFeeTable>();
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
            this.HomeWorkTables = new HashSet<HomeWorkTable>();
        }

        public int StudentID { get; set; }
        [Required(ErrorMessage = "Please Select Session")]
        [Display(Name = "Session:")]
        public int SessionID { get; set; }
        [Required(ErrorMessage = "Please Select Programe")]
        [Display(Name = "Select Program:")]
        public int ProgrameID { get; set; }
        [Required(ErrorMessage = "Please Select Current Class")]
        [Display(Name = "Current Class:")]
        public int ClassID { get; set; }
        [Display(Name = "Created By:")]
        public int UserID { get; set; }
        [Display(Name = "Student Name:")]
        [Required(ErrorMessage = "Please Enter Student Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter Father Name")]
        [Display(Name = "Father Name:")]
        public string FatherName { get; set; }


        [DataType(DataType.Date)]
        [Display(Name = "Date Of Birth:")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateofBirth { get; set; }
        [Display(Name = "Gender:")]
        [Required(ErrorMessage = "Please Enter Gender")]
        public string Gender { get; set; }
        
        [Display(Name = "Contect Number:")]
        [Required(ErrorMessage = "Please Enter Contact No")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone No Must be 11 Number")]
        public string ContactNo { get; set; }
        
        [Required(ErrorMessage = "Please Enter CNIC")]
        [Display(Name = "CNIC/Birth Certificate:")]
        [StringLength(13, MinimumLength = 13, ErrorMessage = "CNIC Must be 13 Number")]
        public string CNIC { get; set; }

        [Required(ErrorMessage = "Please Enter Father CNIC")]
        [Display(Name = "Father CNIC:")]
        [StringLength(13, MinimumLength = 13, ErrorMessage = "F-NIC Must be 13 Number")]
        public string FNIC { get; set; }


        [Required(ErrorMessage = "Please Select Addmission Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Addmission Date:")]
        public System.DateTime AddmissionDate { get; set; }
        [Display(Name = "Previous School:")]
        [Required(ErrorMessage = "Please Enter Previous School Name")]
        public string PreviousSchool { get; set; }
        [Display(Name = "Previous Percentage:")]
        [Required(ErrorMessage = "Please Enter Prevous Percentage")]
        public Nullable<double> PreviousPercentage { get; set; }
        [Required(ErrorMessage = "Please Enter Email Address")]
        [Display(Name = "Email Address:")]
        public string EmailAddress { get; set; }
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Please Enter Permanent Address")]
        [Display(Name = "Permanent Address:")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter Nationality")]
        [Display(Name = "Nationality:")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = "Please Enter Religion")]
        [Display(Name = "Religion:")]
        public string Religion { get; set; }
        [Required(ErrorMessage = "Please Enter Caste")]
        [Display(Name = "Tribe/Caste:")]
        public string TribeorCaste { get; set; }
        [Required(ErrorMessage = "Please Enter Father Occupation")]
        [Display(Name = "Father Occupation:")]
        public string FathersGuardiansOccupationofProfession { get; set; }
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Please Enter Postal Address")]
        [Display(Name = "Postal Address:")]
        public string FathersGuardiansPostalAddress { get; set; }
        [Required(ErrorMessage = "Please Enter Office Phone No")]
        [Display(Name = "Office Phone Number:")]
        public string PhoneOffice { get; set; }
        [Required(ErrorMessage = "Please Enter Resident")]
        [Display(Name = "Resident:")]
        public string PhoneResident { get; set; }

        public string Photo { get; set; }
        [Required(ErrorMessage = "Please Select Student Photo")]

        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceTable> AttendanceTables { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLeavingTable> SchoolLeavingTables { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPromotTable> StudentPromotTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionFeeTable> SubmissionFeeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeWorkTable> HomeWorkTables { get; set; }
    }
}
