//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SubmissionFeeTable
    {
        public int SubmissionFeeID { get; set; }
        public int UserID { get; set; }

        [Required(ErrorMessage = "Please Select Class")]
        public int ClassID { get; set; }

        [Required(ErrorMessage = "Please Select Student")]
        public int StudentID { get; set; }

        [Required(ErrorMessage = "Please Enter Tution Fee")]
        public double Amount { get; set; }

        [Required(ErrorMessage = "Please Select Programe")]
        public int ProgrameID { get; set; }
        [Required(ErrorMessage = "Please Select Tution Fee Submission Date")]
        [DataType(DataType.Date)]
        public System.DateTime SubmissionDate { get; set; }
        [Required(ErrorMessage = "Please Enter Fee Month")]
        public string FeesMonth { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public virtual ClassTable ClassTable { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
